# host: "login.salesforce.com"       # Use test.salesforce.com for sandbox
client_secret: '5826664495915710786'         # This is the Consumer Secret from Salesforce
client_id: '3MVG9Y6d_Btp4xp6xNqHbQc1SUpIWPMmYJtJqCaexLP4ehbqAqcIa37Ks.id8qX.0W91om8W26s3FzXa.dm6s'    # This is the Consumer Key from Salesforce
sobject_module: SFDC_Models       # See below for details on using modules
debugging: true                   # Can be useful while developing
username: "payalgupta1985@gmail.com"
password: "adityagupta1985"