CURRENCIES = [
  {
    "priority"=> 100,
    "iso_code"=> "AED",
    "name"=> "United Arab Emirates Dirham",
    "subunit"=> "Fils",
    "subunit_to_unit"=> 100,
    "symbol_first"=> true,
    "html_entity"=> "",
    "decimal_mark"=> ".",
    "thousands_separator"=> ",",
    "iso_numeric"=> "784"
  },
  {
    "priority"=> 100,
    "iso_code"=> "AFN",
    "name"=> "Afghan Afghani",
    "subunit"=> "Pul",
    "subunit_to_unit"=> 100,
    "symbol_first"=> false,
    "html_entity"=> "",
    "decimal_mark"=> ".",
    "thousands_separator"=> ",",
    "iso_numeric"=> "971"
  },
  {
    "priority"=> 100,
    "iso_code"=> "ALL",
    "name"=> "Albanian Lek",
    "subunit"=> "Qintar",
    "subunit_to_unit"=> 100,
    "symbol_first"=> false,
    "html_entity"=> "",
    "decimal_mark"=> ".",
    "thousands_separator"=> ",",
    "iso_numeric"=> "008"
  },
  {
    "priority"=> 100,
    "iso_code"=> "AMD",
    "name"=> "Armenian Dram",
    "subunit"=> "Luma",
    "subunit_to_unit"=> 100,
    "symbol_first"=> false,
    "html_entity"=> "",
    "decimal_mark"=> ".",
    "thousands_separator"=> ",",
    "iso_numeric"=> "051"
  },
  {
    "priority"=> 100,
    "iso_code"=> "ANG",
    "name"=> "Netherlands Antillean Gulden",
    "subunit"=> "Cent",
    "subunit_to_unit"=> 100,
    "symbol_first"=> true,
    "html_entity"=> "&#x0192;",
    "decimal_mark"=> ",",
    "thousands_separator"=> ".",
    "iso_numeric"=> "532"
  },
  {
    "priority"=> 100,
    "iso_code"=> "AOA",
    "name"=> "Angolan Kwanza",
    "subunit_to_unit"=> 100,
    "symbol_first"=> false,
    "html_entity"=> "",
    "decimal_mark"=> ".",
    "thousands_separator"=> ",",
    "iso_numeric"=> "973"
  },
  {
    "priority"=> 100,
    "iso_code"=> "ARS",
    "name"=> "Argentine Peso",
    "subunit"=> "Centavo",
    "subunit_to_unit"=> 100,
    "symbol_first"=> true,
    "html_entity"=> "&#x20B1;",
    "decimal_mark"=> ",",
    "thousands_separator"=> ".",
    "iso_numeric"=> "032"
  },
  {
    "priority"=> 4,
    "iso_code"=> "AUD",
    "name"=> "Australian Dollar",
    "subunit"=> "Cent",
    "subunit_to_unit"=> 100,
    "symbol_first"=> true,
    "html_entity"=> "$",
    "decimal_mark"=> ".",
    "thousands_separator"=> ",",
    "iso_numeric"=> "036"
  },
  {
    "priority"=> 100,
    "iso_code"=> "AWG",
    "name"=> "Aruban Florin",
    "subunit"=> "Cent",
    "subunit_to_unit"=> 100,
    "symbol_first"=> false,
    "html_entity"=> "&#x0192;",
    "decimal_mark"=> ".",
    "thousands_separator"=> ",",
    "iso_numeric"=> "533"
  },
  {
    "priority"=> 100,
    "iso_code"=> "AZN",
    "name"=> "Azerbaijani Manat",
    "symbol"=> nil,
    "subunit_to_unit"=> 100,
    "symbol_first"=> true,
    "html_entity"=> "",
    "decimal_mark"=> ".",
    "thousands_separator"=> ",",
    "iso_numeric"=> "944"
  },
  {
    "priority"=> 100,
    "iso_code"=> "BAM",
    "name"=> "Bosnia and Herzegovina Convertible Mark",
    "subunit"=> "Fening",
    "subunit_to_unit"=> 100,
    "symbol_first"=> true,
    "html_entity"=> "",
    "decimal_mark"=> ".",
    "thousands_separator"=> ",",
    "iso_numeric"=> "977"
  },
  {
    "priority"=> 100,
    "iso_code"=> "BBD",
    "name"=> "Barbadian Dollar",
    "subunit"=> "Cent",
    "subunit_to_unit"=> 100,
    "symbol_first"=> false,
    "html_entity"=> "$",
    "decimal_mark"=> ".",
    "thousands_separator"=> ",",
    "iso_numeric"=> "052"
  },
  {
    "priority"=> 100,
    "iso_code"=> "BDT",
    "name"=> "Bangladeshi Taka",
    "subunit"=> "Paisa",
    "subunit_to_unit"=> 100,
    "symbol_first"=> true,
    "html_entity"=> "",
    "decimal_mark"=> ".",
    "thousands_separator"=> ",",
    "iso_numeric"=> "050"
  },
  {
    "priority"=> 100,
    "iso_code"=> "BGN",
    "name"=> "Bulgarian Lev",
    "subunit"=> "Stotinka",
    "subunit_to_unit"=> 100,
    "symbol_first"=> true,
    "html_entity"=> "",
    "decimal_mark"=> ".",
    "thousands_separator"=> ",",
    "iso_numeric"=> "975"
  },
  {
    "priority"=> 100,
    "iso_code"=> "BHD",
    "name"=> "Bahraini Dinar",
    "subunit"=> "Fils",
    "subunit_to_unit"=> 1000,
    "symbol_first"=> true,
    "html_entity"=> "",
    "decimal_mark"=> ".",
    "thousands_separator"=> ",",
    "iso_numeric"=> "048"
  },
  {
    "priority"=> 100,
    "iso_code"=> "BIF",
    "name"=> "Burundian Franc",
    "subunit"=> "Centime",
    "subunit_to_unit"=> 100,
    "symbol_first"=> false,
    "html_entity"=> "",
    "decimal_mark"=> ".",
    "thousands_separator"=> ",",
    "iso_numeric"=> "108"
  },
  {
    "priority"=> 100,
    "iso_code"=> "BMD",
    "name"=> "Bermudian Dollar",
    "subunit"=> "Cent",
    "subunit_to_unit"=> 100,
    "symbol_first"=> true,
    "html_entity"=> "$",
    "decimal_mark"=> ".",
    "thousands_separator"=> ",",
    "iso_numeric"=> "060"
  },
  {
    "priority"=> 100,
    "iso_code"=> "BND",
    "name"=> "Brunei Dollar",
    "subunit"=> "Sen",
    "subunit_to_unit"=> 100,
    "symbol_first"=> true,
    "html_entity"=> "$",
    "decimal_mark"=> ".",
    "thousands_separator"=> ",",
    "iso_numeric"=> "096"
  },
  {
    "priority"=> 100,
    "iso_code"=> "BOB",
    "name"=> "Bolivian Boliviano",
    "subunit"=> "Centavo",
    "subunit_to_unit"=> 100,
    "symbol_first"=> true,
    "html_entity"=> "",
    "decimal_mark"=> ".",
    "thousands_separator"=> ",",
    "iso_numeric"=> "068"
  },
  {
    "priority"=> 100,
    "iso_code"=> "BRL",
    "name"=> "Brazilian Real",
    "subunit"=> "Centavo",
    "subunit_to_unit"=> 100,
    "symbol_first"=> true,
    "html_entity"=> "R$",
    "decimal_mark"=> ",",
    "thousands_separator"=> ".",
    "iso_numeric"=> "986"
  },
  {
    "priority"=> 100,
    "iso_code"=> "BSD",
    "name"=> "Bahamian Dollar",
    "subunit"=> "Cent",
    "subunit_to_unit"=> 100,
    "symbol_first"=> true,
    "html_entity"=> "$",
    "decimal_mark"=> ".",
    "thousands_separator"=> ",",
    "iso_numeric"=> "044"
  },
  {
    "priority"=> 100,
    "iso_code"=> "BTN",
    "name"=> "Bhutanese Ngultrum",
    "subunit"=> "Chertrum",
    "subunit_to_unit"=> 100,
    "symbol_first"=> false,
    "html_entity"=> "",
    "decimal_mark"=> ".",
    "thousands_separator"=> ",",
    "iso_numeric"=> "064"
  },
  {
    "priority"=> 100,
    "iso_code"=> "BWP",
    "name"=> "Botswana Pula",
    "subunit"=> "Thebe",
    "subunit_to_unit"=> 100,
    "symbol_first"=> true,
    "html_entity"=> "",
    "decimal_mark"=> ".",
    "thousands_separator"=> ",",
    "iso_numeric"=> "072"
  },
  {
    "priority"=> 100,
    "iso_code"=> "BYR",
    "name"=> "Belarusian Ruble",
    "subunit"=> "Kapyeyka",
    "subunit_to_unit"=> 100,
    "symbol_first"=> false,
    "html_entity"=> "",
    "decimal_mark"=> ".",
    "thousands_separator"=> ",",
    "iso_numeric"=> "974"
  },
  {
    "priority"=> 100,
    "iso_code"=> "BZD",
    "name"=> "Belize Dollar",
    "symbol"=> "$",
    "subunit"=> "Cent",
    "subunit_to_unit"=> 100,
    "symbol_first"=> true,
    "html_entity"=> "$",
    "decimal_mark"=> ".",
    "thousands_separator"=> ",",
    "iso_numeric"=> "084"
  },
  {
    "priority"=> 5,
    "iso_code"=> "CAD",
    "name"=> "Canadian Dollar",
    "symbol"=> "$",
    "subunit"=> "Cent",
    "subunit_to_unit"=> 100,
    "symbol_first"=> true,
    "html_entity"=> "$",
    "decimal_mark"=> ".",
    "thousands_separator"=> ",",
    "iso_numeric"=> "124"
  },
  {
    "priority"=> 100,
    "iso_code"=> "CDF",
    "name"=> "Congolese Franc",
    "symbol"=> "Fr",
    "subunit"=> "Centime",
    "subunit_to_unit"=> 100,
    "symbol_first"=> false,
    "html_entity"=> "",
    "decimal_mark"=> ".",
    "thousands_separator"=> ",",
    "iso_numeric"=> "976"
  },
  {
    "priority"=> 100,
    "iso_code"=> "CHF",
    "name"=> "Swiss Franc",
    "symbol"=> "Fr",
    "subunit"=> "Rappen",
    "subunit_to_unit"=> 100,
    "symbol_first"=> true,
    "html_entity"=> "",
    "decimal_mark"=> ".",
    "thousands_separator"=> ",",
    "iso_numeric"=> "756"
  },
  {
    "priority"=> 100,
    "iso_code"=> "CLP",
    "name"=> "Chilean Peso",
    "symbol"=> "$",
    "subunit"=> "Peso",
    "subunit_to_unit"=> 1,
    "symbol_first"=> true,
    "html_entity"=> "&#x20B1;",
    "decimal_mark"=> ",",
    "thousands_separator"=> ".",
    "iso_numeric"=> "152"
  },
  {
    "priority"=> 100,
    "iso_code"=> "CNY",
    "name"=> "Chinese Renminbi Yuan",
    "subunit"=> "Fen",
    "subunit_to_unit"=> 100,
    "symbol_first"=> true,
    "html_entity"=> "&#x5713;",
    "decimal_mark"=> ".",
    "thousands_separator"=> ",",
    "iso_numeric"=> "156"
  },
  {
    "priority"=> 100,
    "iso_code"=> "COP",
    "name"=> "Colombian Peso",
    "subunit"=> "Centavo",
    "subunit_to_unit"=> 100,
    "symbol_first"=> true,
    "html_entity"=> "&#x20B1;",
    "decimal_mark"=> ",",
    "thousands_separator"=> ".",
    "iso_numeric"=> "170"
  },
  {
    "priority"=> 100,
    "iso_code"=> "CRC",
    "subunit_to_unit"=> 100,
    "symbol_first"=> true,
    "html_entity"=> "&#x20A1;",
    "decimal_mark"=> ",",
    "thousands_separator"=> ".",
    "iso_numeric"=> "188"
  },
  {
    "priority"=> 100,
    "iso_code"=> "CUC",
    "name"=> "Cuban Convertible Peso",
    "subunit"=> "Centavo",
    "subunit_to_unit"=> 100,
    "symbol_first"=> false,
    "html_entity"=> "",
    "decimal_mark"=> ".",
    "thousands_separator"=> ",",
    "iso_numeric"=> "931"
  },
  {
    "priority"=> 100,
    "iso_code"=> "CUP",
    "name"=> "Cuban Peso",
    "symbol"=> "$",
    "subunit"=> "Centavo",
    "subunit_to_unit"=> 100,
    "symbol_first"=> true,
    "html_entity"=> "&#x20B1;",
    "decimal_mark"=> ".",
    "thousands_separator"=> ",",
    "iso_numeric"=> "192"
  },
  {
    "priority"=> 100,
    "iso_code"=> "CVE",
    "name"=> "Cape Verdean Escudo",
    "symbol"=> "$ or Esc",
    "subunit"=> "Centavo",
    "subunit_to_unit"=> 100,
    "symbol_first"=> false,
    "html_entity"=> "",
    "decimal_mark"=> ".",
    "thousands_separator"=> ",",
    "iso_numeric"=> "132"
  },
  {
    "priority"=> 100,
    "iso_code"=> "CZK",
    "name"=> "Czech Koruna",
    "subunit_to_unit"=> 100,
    "symbol_first"=> true,
    "html_entity"=> "",
    "decimal_mark"=> ",",
    "thousands_separator"=> ".",
    "iso_numeric"=> "203"
  },
  {
    "priority"=> 100,
    "iso_code"=> "DJF",
    "name"=> "Djiboutian Franc",
    "symbol"=> "Fr",
    "subunit"=> "Centime",
    "subunit_to_unit"=> 100,
    "symbol_first"=> false,
    "html_entity"=> "",
    "decimal_mark"=> ".",
    "thousands_separator"=> ",",
    "iso_numeric"=> "262"
  },
  {
    "priority"=> 100,
    "iso_code"=> "DKK",
    "name"=> "Danish Krone",
    "symbol"=> "kr",
    "subunit_to_unit"=> 100,
    "symbol_first"=> false,
    "html_entity"=> "",
    "decimal_mark"=> ",",
    "thousands_separator"=> ".",
    "iso_numeric"=> "208"
  },
  {
    "priority"=> 100,
    "iso_code"=> "DOP",
    "name"=> "Dominican Peso",
    "symbol"=> "$",
    "subunit"=> "Centavo",
    "subunit_to_unit"=> 100,
    "symbol_first"=> true,
    "html_entity"=> "&#x20B1;",
    "decimal_mark"=> ".",
    "thousands_separator"=> ",",
    "iso_numeric"=> "214"
  },
  {
    "priority"=> 100,
    "iso_code"=> "DZD",
    "name"=> "Algerian Dinar",
    "subunit"=> "Centime",
    "subunit_to_unit"=> 100,
    "symbol_first"=> false,
    "html_entity"=> "",
    "decimal_mark"=> ".",
    "thousands_separator"=> ",",
    "iso_numeric"=> "012"
  },
  {
    "priority"=> 100,
    "iso_code"=> "EGP",
    "name"=> "Egyptian Pound",
    "subunit"=> "Piastre",
    "subunit_to_unit"=> 100,
    "symbol_first"=> true,
    "html_entity"=> "&#x00A3;",
    "decimal_mark"=> ".",
    "thousands_separator"=> ",",
    "iso_numeric"=> "818"
  },
  {
    "priority"=> 100,
    "iso_code"=> "ERN",
    "name"=> "Eritrean Nakfa",
    "symbol"=> "Nfk",
    "subunit"=> "Cent",
    "subunit_to_unit"=> 100,
    "symbol_first"=> false,
    "html_entity"=> "",
    "decimal_mark"=> ".",
    "thousands_separator"=> ",",
    "iso_numeric"=> "232"
  },
  {
    "priority"=> 100,
    "iso_code"=> "ETB",
    "name"=> "Ethiopian Birr",
    "symbol"=> nil,
    "subunit"=> "Santim",
    "subunit_to_unit"=> 100,
    "symbol_first"=> false,
    "html_entity"=> "",
    "decimal_mark"=> ".",
    "thousands_separator"=> ",",
    "iso_numeric"=> "230"
  },
  {
    "priority"=> 2,
    "iso_code"=> "EUR",
    "name"=> "Euro",
    "subunit"=> "Cent",
    "subunit_to_unit"=> 100,
    "symbol_first"=> true,
    "html_entity"=> "&#x20AC;",
    "decimal_mark"=> ",",
    "thousands_separator"=> ".",
    "iso_numeric"=> "978"
  },
  {
    "priority"=> 100,
    "iso_code"=> "FJD",
    "name"=> "Fijian Dollar",
    "symbol"=> "$",
    "subunit"=> "Cent",
    "subunit_to_unit"=> 100,
    "symbol_first"=> false,
    "html_entity"=> "$",
    "decimal_mark"=> ".",
    "thousands_separator"=> ",",
    "iso_numeric"=> "242"
  },
  {
    "priority"=> 100,
    "iso_code"=> "FKP",
    "name"=> "Falkland Pound",
    "subunit"=> "Penny",
    "subunit_to_unit"=> 100,
    "symbol_first"=> false,
    "html_entity"=> "&#x00A3;",
    "decimal_mark"=> ".",
    "thousands_separator"=> ",",
    "iso_numeric"=> "238"
  },
  {
    "priority"=> 3,
    "iso_code"=> "GBP",
    "name"=> "British Pound",
    "subunit"=> "Penny",
    "subunit_to_unit"=> 100,
    "symbol_first"=> true,
    "html_entity"=> "&#x00A3;",
    "decimal_mark"=> ".",
    "thousands_separator"=> ",",
    "iso_numeric"=> "826"
  },
  {
    "priority"=> 100,
    "iso_code"=> "GEL",
    "name"=> "Georgian Lari",
    "subunit"=> "Tetri",
    "subunit_to_unit"=> 100,
    "symbol_first"=> false,
    "html_entity"=> "",
    "decimal_mark"=> ".",
    "thousands_separator"=> ",",
    "iso_numeric"=> "981"
  },
  {
    "priority"=> 100,
    "iso_code"=> "GHS",
    "name"=> "Ghanaian Cedi",
    "subunit"=> "Pesewa",
    "subunit_to_unit"=> 100,
    "symbol_first"=> true,
    "html_entity"=> "&#x20B5;",
    "decimal_mark"=> ".",
    "thousands_separator"=> ",",
    "iso_numeric"=> "936"
  },
  {
    "priority"=> 100,
    "iso_code"=> "GIP",
    "name"=> "Gibraltar Pound",
    "subunit"=> "Penny",
    "subunit_to_unit"=> 100,
    "symbol_first"=> true,
    "html_entity"=> "&#x00A3;",
    "decimal_mark"=> ".",
    "thousands_separator"=> ",",
    "iso_numeric"=> "292"
  },
  {
    "priority"=> 100,
    "iso_code"=> "GMD",
    "name"=> "Gambian Dalasi",
    "symbol"=> "D",
    "subunit"=> "Butut",
    "subunit_to_unit"=> 100,
    "symbol_first"=> false,
    "html_entity"=> "",
    "decimal_mark"=> ".",
    "thousands_separator"=> ",",
    "iso_numeric"=> "270"
  },
  {
    "priority"=> 100,
    "iso_code"=> "GNF",
    "name"=> "Guinean Franc",
    "symbol"=> "Fr",
    "subunit"=> "Centime",
    "subunit_to_unit"=> 100,
    "symbol_first"=> false,
    "html_entity"=> "",
    "decimal_mark"=> ".",
    "thousands_separator"=> ",",
    "iso_numeric"=> "324"
  },
  {
    "priority"=> 100,
    "iso_code"=> "GTQ",
    "name"=> "Guatemalan Quetzal",
    "symbol"=> "Q",
    "subunit"=> "Centavo",
    "subunit_to_unit"=> 100,
    "symbol_first"=> true,
    "html_entity"=> "",
    "decimal_mark"=> ".",
    "thousands_separator"=> ",",
    "iso_numeric"=> "320"
  },
  {
    "priority"=> 100,
    "iso_code"=> "GYD",
    "name"=> "Guyanese Dollar",
    "symbol"=> "$",
    "subunit"=> "Cent",
    "subunit_to_unit"=> 100,
    "symbol_first"=> false,
    "html_entity"=> "$",
    "decimal_mark"=> ".",
    "thousands_separator"=> ",",
    "iso_numeric"=> "328"
  },
  {
    "priority"=> 100,
    "iso_code"=> "HKD",
    "name"=> "Hong Kong Dollar",
    "symbol"=> "$",
    "subunit"=> "Cent",
    "subunit_to_unit"=> 100,
    "symbol_first"=> true,
    "html_entity"=> "$",
    "decimal_mark"=> ".",
    "thousands_separator"=> ",",
    "iso_numeric"=> "344"
  },
  {
    "priority"=> 100,
    "iso_code"=> "HNL",
    "name"=> "Honduran Lempira",
    "symbol"=> "L",
    "subunit"=> "Centavo",
    "subunit_to_unit"=> 100,
    "symbol_first"=> true,
    "html_entity"=> "",
    "decimal_mark"=> ".",
    "thousands_separator"=> ",",
    "iso_numeric"=> "340"
  },
  {
    "priority"=> 100,
    "iso_code"=> "HRK",
    "name"=> "Croatian Kuna",
    "symbol"=> "kn",
    "subunit"=> "Lipa",
    "subunit_to_unit"=> 100,
    "symbol_first"=> true,
    "html_entity"=> "",
    "decimal_mark"=> ",",
    "thousands_separator"=> ".",
    "iso_numeric"=> "191"
  },
  {
    "priority"=> 100,
    "iso_code"=> "HTG",
    "name"=> "Haitian Gourde",
    "symbol"=> "G",
    "subunit"=> "Centime",
    "subunit_to_unit"=> 100,
    "symbol_first"=> false,
    "html_entity"=> "",
    "decimal_mark"=> ".",
    "thousands_separator"=> ",",
    "iso_numeric"=> "332"
  },
  {
    "priority"=> 100,
    "iso_code"=> "HUF",
    "name"=> "Hungarian Forint",
    "symbol"=> "Ft",
    "subunit_to_unit"=> 100,
    "symbol_first"=> false,
    "html_entity"=> "",
    "decimal_mark"=> ",",
    "thousands_separator"=> ".",
    "iso_numeric"=> "348"
  },
  {
    "priority"=> 100,
    "iso_code"=> "IDR",
    "name"=> "Indonesian Rupiah",
    "symbol"=> "Rp",
    "subunit"=> "Sen",
    "subunit_to_unit"=> 100,
    "symbol_first"=> true,
    "html_entity"=> "",
    "decimal_mark"=> ",",
    "thousands_separator"=> ".",
    "iso_numeric"=> "360"
  },
  {
    "priority"=> 100,
    "iso_code"=> "ILS",
    "name"=> "Israeli New Sheqel",
    "subunit"=> "Agora",
    "subunit_to_unit"=> 100,
    "symbol_first"=> true,
    "html_entity"=> "&#x20AA;",
    "decimal_mark"=> ".",
    "thousands_separator"=> ",",
    "iso_numeric"=> "376"
  },
  {
    "priority"=> 100,
    "iso_code"=> "INR",
    "name"=> "Indian Rupee",
    "subunit"=> "Paisa",
    "subunit_to_unit"=> 100,
    "symbol_first"=> true,
    "html_entity"=> "&#x20A8;",
    "decimal_mark"=> ".",
    "thousands_separator"=> ",",
    "iso_numeric"=> "356"
  },
  {
    "priority"=> 100,
    "iso_code"=> "IQD",
    "name"=> "Iraqi Dinar",
    "subunit"=> "Fils",
    "subunit_to_unit"=> 1000,
    "symbol_first"=> false,
    "html_entity"=> "",
    "decimal_mark"=> ".",
    "thousands_separator"=> ",",
    "iso_numeric"=> "368"
  },
  {
    "priority"=> 100,
    "iso_code"=> "IRR",
    "name"=> "Iranian Rial",
    "subunit"=> "Dinar",
    "subunit_to_unit"=> 100,
    "symbol_first"=> true,
    "html_entity"=> "&#xFDFC;",
    "decimal_mark"=> ".",
    "thousands_separator"=> ",",
    "iso_numeric"=> "364"
  },
  {
    "priority"=> 100,
    "iso_code"=> "ISK",
    "symbol"=> "kr",
    "subunit"=> "Eyrir",
    "subunit_to_unit"=> 100,
    "symbol_first"=> true,
    "html_entity"=> "",
    "decimal_mark"=> ",",
    "thousands_separator"=> ".",
    "iso_numeric"=> "352"
  },
  {
    "priority"=> 100,
    "iso_code"=> "JMD",
    "name"=> "Jamaican Dollar",
    "symbol"=> "$",
    "subunit"=> "Cent",
    "subunit_to_unit"=> 100,
    "symbol_first"=> true,
    "html_entity"=> "$",
    "decimal_mark"=> ".",
    "thousands_separator"=> ",",
    "iso_numeric"=> "388"
  },
  {
    "priority"=> 100,
    "iso_code"=> "JOD",
    "name"=> "Jordanian Dinar",
    "subunit"=> "Piastre",
    "subunit_to_unit"=> 100,
    "symbol_first"=> true,
    "html_entity"=> "",
    "decimal_mark"=> ".",
    "thousands_separator"=> ",",
    "iso_numeric"=> "400"
  },
  {
    "priority"=> 6,
    "iso_code"=> "JPY",
    "name"=> "Japanese Yen",
    "subunit"=> nil,
    "subunit_to_unit"=> 1,
    "symbol_first"=> true,
    "html_entity"=> "&#x00A5;",
    "decimal_mark"=> ".",
    "thousands_separator"=> ",",
    "iso_numeric"=> "392"
  },
  {
    "priority"=> 100,
    "iso_code"=> "KES",
    "name"=> "Kenyan Shilling",
    "symbol"=> "Sh",
    "subunit"=> "Cent",
    "subunit_to_unit"=> 100,
    "symbol_first"=> true,
    "html_entity"=> "",
    "decimal_mark"=> ".",
    "thousands_separator"=> ",",
    "iso_numeric"=> "404"
  },
  {
    "priority"=> 100,
    "iso_code"=> "KGS",
    "name"=> "Kyrgyzstani Som",
    "symbol"=> nil,
    "subunit"=> "Tyiyn",
    "subunit_to_unit"=> 100,
    "symbol_first"=> false,
    "html_entity"=> "",
    "decimal_mark"=> ".",
    "thousands_separator"=> ",",
    "iso_numeric"=> "417"
  },
  {
    "priority"=> 100,
    "iso_code"=> "KHR",
    "name"=> "Cambodian Riel",
    "subunit"=> "Sen",
    "subunit_to_unit"=> 100,
    "symbol_first"=> false,
    "html_entity"=> "&#x17DB;",
    "decimal_mark"=> ".",
    "thousands_separator"=> ",",
    "iso_numeric"=> "116"
  },
  {
    "priority"=> 100,
    "iso_code"=> "KMF",
    "name"=> "Comorian Franc",
    "subunit"=> "Centime",
    "subunit_to_unit"=> 100,
    "symbol_first"=> false,
    "html_entity"=> "",
    "decimal_mark"=> ".",
    "thousands_separator"=> ",",
    "iso_numeric"=> "174"
  },
  {
    "priority"=> 100,
    "iso_code"=> "KPW",
    "name"=> "North Korean Won",
    "subunit_to_unit"=> 100,
    "symbol_first"=> false,
    "html_entity"=> "&#x20A9;",
    "decimal_mark"=> ".",
    "thousands_separator"=> ",",
    "iso_numeric"=> "408"
  },
  {
    "priority"=> 100,
    "iso_code"=> "KRW",
    "name"=> "South Korean Won",
    "subunit"=> "Jeon",
    "subunit_to_unit"=> 100,
    "symbol_first"=> true,
    "html_entity"=> "&#x20A9;",
    "decimal_mark"=> ".",
    "thousands_separator"=> ",",
    "iso_numeric"=> "410"
  },
  {
    "priority"=> 100,
    "iso_code"=> "KWD",
    "name"=> "Kuwaiti Dinar",
    "subunit"=> "Fils",
    "subunit_to_unit"=> 1000,
    "symbol_first"=> true,
    "html_entity"=> "",
    "decimal_mark"=> ".",
    "thousands_separator"=> ",",
    "iso_numeric"=> "414"
  },
  {
    "priority"=> 100,
    "iso_code"=> "KYD",
    "name"=> "Cayman Islands Dollar",
    "symbol"=> "$",
    "subunit"=> "Cent",
    "subunit_to_unit"=> 100,
    "symbol_first"=> true,
    "html_entity"=> "$",
    "decimal_mark"=> ".",
    "thousands_separator"=> ",",
    "iso_numeric"=> "136"
  },
  {
    "priority"=> 100,
    "iso_code"=> "KZT",
    "name"=> "Kazakhstani Tenge",
    "subunit"=> "Tiyn",
    "subunit_to_unit"=> 100,
    "symbol_first"=> false,
    "html_entity"=> "",
    "decimal_mark"=> ".",
    "thousands_separator"=> ",",
    "iso_numeric"=> "398"
  },
  {
    "priority"=> 100,
    "iso_code"=> "LAK",
    "name"=> "Lao Kip",
    "subunit"=> "Att",
    "subunit_to_unit"=> 100,
    "symbol_first"=> false,
    "html_entity"=> "&#x20AD;",
    "decimal_mark"=> ".",
    "thousands_separator"=> ",",
    "iso_numeric"=> "418"
  },
  {
    "priority"=> 100,
    "iso_code"=> "LBP",
    "name"=> "Lebanese Pound",
    "subunit"=> "Piastre",
    "subunit_to_unit"=> 100,
    "symbol_first"=> true,
    "html_entity"=> "&#x00A3;",
    "decimal_mark"=> ".",
    "thousands_separator"=> ",",
    "iso_numeric"=> "422"
  },
  {
    "priority"=> 100,
    "iso_code"=> "LKR",
    "name"=> "Sri Lankan Rupee",
    "subunit"=> "Cent",
    "subunit_to_unit"=> 100,
    "symbol_first"=> false,
    "html_entity"=> "&#x0BF9;",
    "decimal_mark"=> ".",
    "thousands_separator"=> ",",
    "iso_numeric"=> "144"
  },
  {
    "priority"=> 100,
    "iso_code"=> "LRD",
    "name"=> "Liberian Dollar",
    "symbol"=> "$",
    "subunit"=> "Cent",
    "subunit_to_unit"=> 100,
    "symbol_first"=> false,
    "html_entity"=> "$",
    "decimal_mark"=> ".",
    "thousands_separator"=> ",",
    "iso_numeric"=> "430"
  },
  {
    "priority"=> 100,
    "iso_code"=> "LSL",
    "name"=> "Lesotho Loti",
    "symbol"=> "L",
    "subunit"=> "Sente",
    "subunit_to_unit"=> 100,
    "symbol_first"=> false,
    "html_entity"=> "",
    "decimal_mark"=> ".",
    "thousands_separator"=> ",",
    "iso_numeric"=> "426"
  },
  {
    "priority"=> 100,
    "iso_code"=> "LTL",
    "name"=> "Lithuanian Litas",
    "symbol"=> "Lt",
    "subunit"=> "Centas",
    "subunit_to_unit"=> 100,
    "symbol_first"=> false,
    "html_entity"=> "",
    "decimal_mark"=> ".",
    "thousands_separator"=> ",",
    "iso_numeric"=> "440"
  },
  {
    "priority"=> 100,
    "iso_code"=> "LVL",
    "name"=> "Latvian Lats",
    "symbol"=> "Ls",
    "subunit_to_unit"=> 100,
    "symbol_first"=> true,
    "html_entity"=> "",
    "decimal_mark"=> ".",
    "thousands_separator"=> ",",
    "iso_numeric"=> "428"
  },
  {
    "priority"=> 100,
    "iso_code"=> "LYD",
    "name"=> "Libyan Dinar",
    "subunit"=> "Dirham",
    "subunit_to_unit"=> 1000,
    "symbol_first"=> false,
    "html_entity"=> "",
    "decimal_mark"=> ".",
    "thousands_separator"=> ",",
    "iso_numeric"=> "434"
  },
  {
    "priority"=> 100,
    "iso_code"=> "MAD",
    "name"=> "Moroccan Dirham",
    "subunit"=> "Centime",
    "subunit_to_unit"=> 100,
    "symbol_first"=> false,
    "html_entity"=> "",
    "decimal_mark"=> ".",
    "thousands_separator"=> ",",
    "iso_numeric"=> "504"
  },
  {
    "priority"=> 100,
    "iso_code"=> "MDL",
    "name"=> "Moldovan Leu",
    "symbol"=> "L",
    "subunit"=> "Ban",
    "subunit_to_unit"=> 100,
    "symbol_first"=> false,
    "html_entity"=> "",
    "decimal_mark"=> ".",
    "thousands_separator"=> ",",
    "iso_numeric"=> "498"
  },
  {
    "priority"=> 100,
    "iso_code"=> "MGA",
    "name"=> "Malagasy Ariary",
    "symbol"=> nil,
    "subunit"=> "Iraimbilanja",
    "subunit_to_unit"=> 5,
    "symbol_first"=> false,
    "html_entity"=> "",
    "decimal_mark"=> ".",
    "thousands_separator"=> ",",
    "iso_numeric"=> "969"
  },
  {
    "priority"=> 100,
    "iso_code"=> "MKD",
    "name"=> "Macedonian Denar",
    "subunit"=> "Deni",
    "subunit_to_unit"=> 100,
    "symbol_first"=> false,
    "html_entity"=> "",
    "decimal_mark"=> ".",
    "thousands_separator"=> ",",
    "iso_numeric"=> "807"
  },
  {
    "priority"=> 100,
    "iso_code"=> "MMK",
    "name"=> "Myanmar Kyat",
    "symbol"=> "K",
    "subunit"=> "Pya",
    "subunit_to_unit"=> 100,
    "symbol_first"=> false,
    "html_entity"=> "",
    "decimal_mark"=> ".",
    "thousands_separator"=> ",",
    "iso_numeric"=> "104"
  },
  {
    "priority"=> 100,
    "iso_code"=> "MNT",
    "subunit_to_unit"=> 100,
    "symbol_first"=> false,
    "html_entity"=> "&#x20AE;",
    "decimal_mark"=> ".",
    "thousands_separator"=> ",",
    "iso_numeric"=> "496"
  },
  {
    "priority"=> 100,
    "iso_code"=> "MOP",
    "name"=> "Macanese Pataca",
    "symbol"=> "P",
    "subunit"=> "Avo",
    "subunit_to_unit"=> 100,
    "symbol_first"=> false,
    "html_entity"=> "",
    "decimal_mark"=> ".",
    "thousands_separator"=> ",",
    "iso_numeric"=> "446"
  },
  {
    "priority"=> 100,
    "iso_code"=> "MRO",
    "name"=> "Mauritanian Ouguiya",
    "symbol"=> "UM",
    "subunit"=> "Khoums",
    "subunit_to_unit"=> 5,
    "symbol_first"=> false,
    "html_entity"=> "",
    "decimal_mark"=> ".",
    "thousands_separator"=> ",",
    "iso_numeric"=> "478"
  },
  {
    "priority"=> 100,
    "iso_code"=> "MUR",
    "name"=> "Mauritian Rupee",
    "subunit"=> "Cent",
    "subunit_to_unit"=> 100,
    "symbol_first"=> true,
    "html_entity"=> "&#x20A8;",
    "decimal_mark"=> ".",
    "thousands_separator"=> ",",
    "iso_numeric"=> "480"
  },
  {
    "priority"=> 100,
    "iso_code"=> "MVR",
    "name"=> "Maldivian Rufiyaa",
    "subunit"=> "Laari",
    "subunit_to_unit"=> 100,
    "symbol_first"=> false,
    "html_entity"=> "",
    "decimal_mark"=> ".",
    "thousands_separator"=> ",",
    "iso_numeric"=> "462"
  },
  {
    "priority"=> 100,
    "iso_code"=> "MWK",
    "name"=> "Malawian Kwacha",
    "symbol"=> "MK",
    "subunit"=> "Tambala",
    "subunit_to_unit"=> 100,
    "symbol_first"=> false,
    "html_entity"=> "",
    "decimal_mark"=> ".",
    "thousands_separator"=> ",",
    "iso_numeric"=> "454"
  },
  {
    "priority"=> 100,
    "iso_code"=> "MXN",
    "name"=> "Mexican Peso",
    "symbol"=> "$",
    "subunit"=> "Centavo",
    "subunit_to_unit"=> 100,
    "symbol_first"=> true,
    "html_entity"=> "$",
    "decimal_mark"=> ".",
    "thousands_separator"=> ",",
    "iso_numeric"=> "484"
  },
  {
    "priority"=> 100,
    "iso_code"=> "MYR",
    "name"=> "Malaysian Ringgit",
    "symbol"=> "RM",
    "subunit"=> "Sen",
    "subunit_to_unit"=> 100,
    "symbol_first"=> true,
    "html_entity"=> "",
    "decimal_mark"=> ".",
    "thousands_separator"=> ",",
    "iso_numeric"=> "458"
  },
  {
    "priority"=> 100,
    "iso_code"=> "MZN",
    "name"=> "Mozambican Metical",
    "symbol"=> "MTn",
    "subunit"=> "Centavo",
    "subunit_to_unit"=> 100,
    "symbol_first"=> true,
    "html_entity"=> "",
    "decimal_mark"=> ",",
    "thousands_separator"=> ".",
    "iso_numeric"=> "943"
  },
  {
    "priority"=> 100,
    "iso_code"=> "NAD",
    "name"=> "Namibian Dollar",
    "symbol"=> "$",
    "subunit"=> "Cent",
    "subunit_to_unit"=> 100,
    "symbol_first"=> false,
    "html_entity"=> "$",
    "decimal_mark"=> ".",
    "thousands_separator"=> ",",
    "iso_numeric"=> "516"
  },
  {
    "priority"=> 100,
    "iso_code"=> "NGN",
    "name"=> "Nigerian Naira",
    "subunit"=> "Kobo",
    "subunit_to_unit"=> 100,
    "symbol_first"=> false,
    "html_entity"=> "&#x20A6;",
    "decimal_mark"=> ".",
    "thousands_separator"=> ",",
    "iso_numeric"=> "566"
  },
  {
    "priority"=> 100,
    "iso_code"=> "NIO",
    "symbol"=> "C$",
    "subunit"=> "Centavo",
    "subunit_to_unit"=> 100,
    "symbol_first"=> false,
    "html_entity"=> "",
    "decimal_mark"=> ".",
    "thousands_separator"=> ",",
    "iso_numeric"=> "558"
  },
  {
    "priority"=> 100,
    "iso_code"=> "NOK",
    "name"=> "Norwegian Krone",
    "symbol"=> "kr",
    "subunit_to_unit"=> 100,
    "symbol_first"=> true,
    "html_entity"=> "kr",
    "decimal_mark"=> ",",
    "thousands_separator"=> ".",
    "iso_numeric"=> "578"
  },
  {
    "priority"=> 100,
    "iso_code"=> "NPR",
    "name"=> "Nepalese Rupee",
    "subunit"=> "Paisa",
    "subunit_to_unit"=> 100,
    "symbol_first"=> true,
    "html_entity"=> "&#x20A8;",
    "decimal_mark"=> ".",
    "thousands_separator"=> ",",
    "iso_numeric"=> "524"
  },
  {
    "priority"=> 100,
    "iso_code"=> "NZD",
    "name"=> "New Zealand Dollar",
    "symbol"=> "$",
    "subunit"=> "Cent",
    "subunit_to_unit"=> 100,
    "symbol_first"=> true,
    "html_entity"=> "$",
    "decimal_mark"=> ".",
    "thousands_separator"=> ",",
    "iso_numeric"=> "554"
  },
  {
    "priority"=> 100,
    "iso_code"=> "OMR",
    "name"=> "Omani Rial",
    "subunit"=> "Baisa",
    "subunit_to_unit"=> 1000,
    "symbol_first"=> true,
    "html_entity"=> "&#xFDFC;",
    "decimal_mark"=> ".",
    "thousands_separator"=> ",",
    "iso_numeric"=> "512"
  },
  {
    "priority"=> 100,
    "iso_code"=> "PAB",
    "name"=> "Panamanian Balboa",
    "subunit_to_unit"=> 100,
    "symbol_first"=> false,
    "html_entity"=> "",
    "decimal_mark"=> ".",
    "thousands_separator"=> ",",
    "iso_numeric"=> "590"
  },
  {
    "priority"=> 100,
    "iso_code"=> "PEN",
    "name"=> "Peruvian Nuevo Sol",
    "symbol"=> "S/.",
    "subunit_to_unit"=> 100,
    "symbol_first"=> true,
    "html_entity"=> "S/.",
    "decimal_mark"=> ".",
    "thousands_separator"=> ",",
    "iso_numeric"=> "604"
  },
  {
    "priority"=> 100,
    "iso_code"=> "PGK",
    "name"=> "Papua New Guinean Kina",
    "symbol"=> "K",
    "subunit"=> "Toea",
    "subunit_to_unit"=> 100,
    "symbol_first"=> false,
    "html_entity"=> "",
    "decimal_mark"=> ".",
    "thousands_separator"=> ",",
    "iso_numeric"=> "598"
  },
  {
    "priority"=> 100,
    "iso_code"=> "PHP",
    "name"=> "Philippine Peso",
    "subunit"=> "Centavo",
    "subunit_to_unit"=> 100,
    "symbol_first"=> true,
    "html_entity"=> "&#x20B1;",
    "decimal_mark"=> ".",
    "thousands_separator"=> ",",
    "iso_numeric"=> "608"
  },
  {
    "priority"=> 100,
    "iso_code"=> "PKR",
    "name"=> "Pakistani Rupee",
    "subunit"=> "Paisa",
    "subunit_to_unit"=> 100,
    "symbol_first"=> true,
    "html_entity"=> "&#x20A8;",
    "decimal_mark"=> ".",
    "thousands_separator"=> ",",
    "iso_numeric"=> "586"
  },
  {
    "priority"=> 100,
    "iso_code"=> "PLN",
    "subunit"=> "Grosz",
    "subunit_to_unit"=> 100,
    "symbol_first"=> false,
    "html_entity"=> "",
    "decimal_mark"=> ",",
    "thousands_separator"=> " ",
    "iso_numeric"=> "985"
  },
  {
    "priority"=> 100,
    "iso_code"=> "PYG",
    "subunit_to_unit"=> 100,
    "symbol_first"=> true,
    "html_entity"=> "&#x20B2;",
    "decimal_mark"=> ".",
    "thousands_separator"=> ",",
    "iso_numeric"=> "600"
  },
  {
    "priority"=> 100,
    "iso_code"=> "QAR",
    "name"=> "Qatari Riyal",
    "subunit"=> "Dirham",
    "subunit_to_unit"=> 100,
    "symbol_first"=> false,
    "html_entity"=> "&#xFDFC;",
    "decimal_mark"=> ".",
    "thousands_separator"=> ",",
    "iso_numeric"=> "634"
  },
  {
    "priority"=> 100,
    "iso_code"=> "RON",
    "name"=> "Romanian Leu",
    "symbol"=> "L",
    "subunit"=> "Ban",
    "subunit_to_unit"=> 100,
    "symbol_first"=> true,
    "html_entity"=> "",
    "decimal_mark"=> ",",
    "thousands_separator"=> ".",
    "iso_numeric"=> "946"
  },
  {
    "priority"=> 100,
    "iso_code"=> "RSD",
    "name"=> "Serbian Dinar",
    "subunit"=> "Para",
    "subunit_to_unit"=> 100,
    "symbol_first"=> true,
    "html_entity"=> "",
    "decimal_mark"=> ".",
    "thousands_separator"=> ",",
    "iso_numeric"=> "941"
  },
  {
    "priority"=> 100,
    "iso_code"=> "RUB",
    "name"=> "Russian Ruble",
    "subunit"=> "Kopek",
    "subunit_to_unit"=> 100,
    "symbol_first"=> false,
    "html_entity"=> "&#x0440;&#x0443;&#x0431;",
    "decimal_mark"=> ",",
    "thousands_separator"=> ".",
    "iso_numeric"=> "643"
  },
  {
    "priority"=> 100,
    "iso_code"=> "RWF",
    "name"=> "Rwandan Franc",
    "symbol"=> "Fr",
    "subunit"=> "Centime",
    "subunit_to_unit"=> 100,
    "symbol_first"=> false,
    "html_entity"=> "",
    "decimal_mark"=> ".",
    "thousands_separator"=> ",",
    "iso_numeric"=> "646"
  },
  {
    "priority"=> 100,
    "iso_code"=> "SAR",
    "name"=> "Saudi Riyal",
    "subunit"=> "Hallallah",
    "subunit_to_unit"=> 100,
    "symbol_first"=> true,
    "html_entity"=> "&#xFDFC;",
    "decimal_mark"=> ".",
    "thousands_separator"=> ",",
    "iso_numeric"=> "682"
  },
  {
    "priority"=> 100,
    "iso_code"=> "SBD",
    "name"=> "Solomon Islands Dollar",
    "symbol"=> "$",
    "subunit"=> "Cent",
    "subunit_to_unit"=> 100,
    "symbol_first"=> false,
    "html_entity"=> "$",
    "decimal_mark"=> ".",
    "thousands_separator"=> ",",
    "iso_numeric"=> "090"
  },
  {
    "priority"=> 100,
    "iso_code"=> "SCR",
    "name"=> "Seychellois Rupee",
    "subunit"=> "Cent",
    "subunit_to_unit"=> 100,
    "symbol_first"=> false,
    "html_entity"=> "&#x20A8;",
    "decimal_mark"=> ".",
    "thousands_separator"=> ",",
    "iso_numeric"=> "690"
  },
  {
    "priority"=> 100,
    "iso_code"=> "SDG",
    "name"=> "Sudanese Pound",
    "subunit"=> "Piastre",
    "subunit_to_unit"=> 100,
    "symbol_first"=> true,
    "html_entity"=> "",
    "decimal_mark"=> ".",
    "thousands_separator"=> ",",
    "iso_numeric"=> "938"
  },
  {
    "priority"=> 100,
    "iso_code"=> "SEK",
    "name"=> "Swedish Krona",
    "symbol"=> "kr",
    "subunit_to_unit"=> 100,
    "symbol_first"=> true,
    "html_entity"=> "",
    "decimal_mark"=> ".",
    "thousands_separator"=> ",",
    "iso_numeric"=> "752"
  },
  {
    "priority"=> 100,
    "iso_code"=> "SGD",
    "name"=> "Singapore Dollar",
    "symbol"=> "$",
    "subunit"=> "Cent",
    "subunit_to_unit"=> 100,
    "symbol_first"=> true,
    "html_entity"=> "$",
    "decimal_mark"=> ".",
    "thousands_separator"=> ",",
    "iso_numeric"=> "702"
  },
  {
    "priority"=> 100,
    "iso_code"=> "SHP",
    "name"=> "Saint Helenian",
    "subunit"=> "Penny",
    "subunit_to_unit"=> 100,
    "symbol_first"=> false,
    "html_entity"=> "&#x00A3;",
    "decimal_mark"=> ".",
    "thousands_separator"=> ",",
    "iso_numeric"=> "654"
  },
  {
    "priority"=> 100,
    "iso_code"=> "SKK",
    "name"=> "Slovak Koruna",
    "symbol"=> "Sk",
    "subunit"=> "Halier",
    "subunit_to_unit"=> 100,
    "symbol_first"=> true,
    "html_entity"=> "",
    "decimal_mark"=> ".",
    "thousands_separator"=> ",",
    "iso_numeric"=> "703"
  },
  {
    "priority"=> 100,
    "iso_code"=> "SLL",
    "name"=> "Sierra Leonean Leone",
    "symbol"=> "Le",
    "subunit"=> "Cent",
    "subunit_to_unit"=> 100,
    "symbol_first"=> false,
    "html_entity"=> "",
    "decimal_mark"=> ".",
    "thousands_separator"=> ",",
    "iso_numeric"=> "694"
  },
  {
    "priority"=> 100,
    "iso_code"=> "SOS",
    "name"=> "Somali Shilling",
    "symbol"=> "Sh",
    "subunit"=> "Cent",
    "subunit_to_unit"=> 100,
    "symbol_first"=> false,
    "html_entity"=> "",
    "decimal_mark"=> ".",
    "thousands_separator"=> ",",
    "iso_numeric"=> "706"
  },
  {
    "priority"=> 100,
    "iso_code"=> "SRD",
    "name"=> "Surinamese Dollar",
    "symbol"=> "$",
    "subunit"=> "Cent",
    "subunit_to_unit"=> 100,
    "symbol_first"=> false,
    "html_entity"=> "",
    "decimal_mark"=> ".",
    "thousands_separator"=> ",",
    "iso_numeric"=> "968"
  },
  {
    "priority"=> 100,
    "iso_code"=> "STD",
    "subunit_to_unit"=> 100,
    "symbol_first"=> false,
    "html_entity"=> "",
    "decimal_mark"=> ".",
    "thousands_separator"=> ",",
    "iso_numeric"=> "678"
  },
  {
    "priority"=> 100,
    "iso_code"=> "SVC",
    "subunit"=> "Centavo",
    "subunit_to_unit"=> 100,
    "symbol_first"=> true,
    "html_entity"=> "&#x20A1;",
    "decimal_mark"=> ".",
    "thousands_separator"=> ",",
    "iso_numeric"=> "222"
  },
  {
    "priority"=> 100,
    "iso_code"=> "SYP",
    "name"=> "Syrian Pound",
    "subunit"=> "Piastre",
    "subunit_to_unit"=> 100,
    "symbol_first"=> false,
    "html_entity"=> "&#x00A3;",
    "decimal_mark"=> ".",
    "thousands_separator"=> ",",
    "iso_numeric"=> "760"
  },
  {
    "priority"=> 100,
    "iso_code"=> "SZL",
    "name"=> "Swazi Lilangeni",
    "symbol"=> "L",
    "subunit"=> "Cent",
    "subunit_to_unit"=> 100,
    "symbol_first"=> true,
    "html_entity"=> "",
    "decimal_mark"=> ".",
    "thousands_separator"=> ",",
    "iso_numeric"=> "748"
  },
  {
    "priority"=> 100,
    "iso_code"=> "THB",
    "name"=> "Thai Baht",
    "subunit"=> "Satang",
    "subunit_to_unit"=> 100,
    "symbol_first"=> true,
    "html_entity"=> "&#x0E3F;",
    "decimal_mark"=> ".",
    "thousands_separator"=> ",",
    "iso_numeric"=> "764"
  },
  {
    "priority"=> 100,
    "iso_code"=> "TJS",
    "name"=> "Tajikistani Somoni",
    "subunit"=> "Diram",
    "subunit_to_unit"=> 100,
    "symbol_first"=> false,
    "html_entity"=> "",
    "decimal_mark"=> ".",
    "thousands_separator"=> ",",
    "iso_numeric"=> "972"
  },
  {
    "priority"=> 100,
    "iso_code"=> "TMM",
    "name"=> "Turkmenistani Manat",
    "symbol"=> "m",
    "subunit"=> "Tennesi",
    "subunit_to_unit"=> 100,
    "symbol_first"=> false,
    "html_entity"=> "",
    "decimal_mark"=> ".",
    "thousands_separator"=> ",",
    "iso_numeric"=> "795"
  },
  {
    "priority"=> 100,
    "iso_code"=> "TND",
    "name"=> "Tunisian Dinar",
    "subunit"=> "Millime",
    "subunit_to_unit"=> 1000,
    "symbol_first"=> false,
    "html_entity"=> "",
    "decimal_mark"=> ".",
    "thousands_separator"=> ",",
    "iso_numeric"=> "788"
  },
  {
    "priority"=> 100,
    "iso_code"=> "TOP",
    "symbol"=> "T$",
    "subunit"=> "Seniti",
    "subunit_to_unit"=> 100,
    "symbol_first"=> true,
    "html_entity"=> "",
    "decimal_mark"=> ".",
    "thousands_separator"=> ",",
    "iso_numeric"=> "776"
  },
  {
    "priority"=> 100,
    "iso_code"=> "TRY",
    "name"=> "Turkish Lira",
    "symbol"=> "TL",
    "subunit_to_unit"=> 100,
    "symbol_first"=> false,
    "html_entity"=> "",
    "decimal_mark"=> ".",
    "thousands_separator"=> ",",
    "iso_numeric"=> "949"
  },
  {
    "priority"=> 100,
    "iso_code"=> "TTD",
    "name"=> "Trinidad and Tobago Dollar",
    "symbol"=> "$",
    "subunit"=> "Cent",
    "subunit_to_unit"=> 100,
    "symbol_first"=> false,
    "html_entity"=> "$",
    "decimal_mark"=> ".",
    "thousands_separator"=> ",",
    "iso_numeric"=> "780"
  },
  {
    "priority"=> 100,
    "iso_code"=> "TWD",
    "name"=> "New Taiwan Dollar",
    "symbol"=> "$",
    "subunit"=> "Cent",
    "subunit_to_unit"=> 100,
    "symbol_first"=> false,
    "html_entity"=> "$",
    "decimal_mark"=> ".",
    "thousands_separator"=> ",",
    "iso_numeric"=> "901"
  },
  {
    "priority"=> 100,
    "iso_code"=> "TZS",
    "name"=> "Tanzanian Shilling",
    "symbol"=> "Sh",
    "subunit"=> "Cent",
    "subunit_to_unit"=> 100,
    "symbol_first"=> true,
    "html_entity"=> "",
    "decimal_mark"=> ".",
    "thousands_separator"=> ",",
    "iso_numeric"=> "834"
  },
  {
    "priority"=> 100,
    "iso_code"=> "UAH",
    "name"=> "Ukrainian Hryvnia",
    "subunit"=> "Kopiyka",
    "subunit_to_unit"=> 100,
    "symbol_first"=> false,
    "html_entity"=> "&#x20B4",
    "decimal_mark"=> ".",
    "thousands_separator"=> ",",
    "iso_numeric"=> "980"
  },
  {
    "priority"=> 100,
    "iso_code"=> "UGX",
    "name"=> "Ugandan Shilling",
    "symbol"=> "Sh",
    "subunit"=> "Cent",
    "subunit_to_unit"=> 100,
    "symbol_first"=> false,
    "html_entity"=> "",
    "decimal_mark"=> ".",
    "thousands_separator"=> ",",
    "iso_numeric"=> "800"
  },
  {
    "priority"=> 1,
    "iso_code"=> "USD",
    "name"=> "United States Dollar",
    "symbol"=> "$",
    "subunit"=> "Cent",
    "subunit_to_unit"=> 100,
    "symbol_first"=> true,
    "html_entity"=> "$",
    "decimal_mark"=> ".",
    "thousands_separator"=> ",",
    "iso_numeric"=> "840"
  },
  {
    "priority"=> 100,
    "iso_code"=> "UYU",
    "name"=> "Uruguayan Peso",
    "symbol"=> "$",
    "subunit_to_unit"=> 100,
    "symbol_first"=> true,
    "html_entity"=> "&#x20B1;",
    "decimal_mark"=> ",",
    "thousands_separator"=> ".",
    "iso_numeric"=> "858"
  },
  {
    "priority"=> 100,
    "iso_code"=> "UZS",
    "name"=> "Uzbekistani Som",
    "symbol"=> nil,
    "subunit"=> "Tiyin",
    "subunit_to_unit"=> 100,
    "symbol_first"=> false,
    "html_entity"=> "",
    "decimal_mark"=> ".",
    "thousands_separator"=> ",",
    "iso_numeric"=> "860"
  },
  {
    "priority"=> 100,
    "iso_code"=> "VEF",
    "subunit_to_unit"=> 100,
    "symbol_first"=> true,
    "html_entity"=> "",
    "decimal_mark"=> ",",
    "thousands_separator"=> ".",
    "iso_numeric"=> "937"
  },
  {
    "priority"=> 100,
    "iso_code"=> "VND",
    "subunit_to_unit"=> 10,
    "symbol_first"=> true,
    "html_entity"=> "&#x20AB;",
    "decimal_mark"=> ",",
    "thousands_separator"=> ".",
    "iso_numeric"=> "704"
  },
  {
    "priority"=> 100,
    "iso_code"=> "VUV",
    "subunit"=> nil,
    "subunit_to_unit"=> 1,
    "symbol_first"=> true,
    "html_entity"=> "",
    "decimal_mark"=> ".",
    "thousands_separator"=> ",",
    "iso_numeric"=> "548"
  },
  {
    "priority"=> 100,
    "iso_code"=> "WST",
    "name"=> "Samoan Tala",
    "symbol"=> "T",
    "subunit"=> "Sene",
    "subunit_to_unit"=> 100,
    "symbol_first"=> false,
    "html_entity"=> "",
    "decimal_mark"=> ".",
    "thousands_separator"=> ",",
    "iso_numeric"=> "882"
  },
  {
    "priority"=> 100,
    "iso_code"=> "XAF",
    "name"=> "Central African Cfa Franc",
    "symbol"=> "Fr",
    "subunit"=> "Centime",
    "subunit_to_unit"=> 100,
    "symbol_first"=> false,
    "html_entity"=> "",
    "decimal_mark"=> ".",
    "thousands_separator"=> ",",
    "iso_numeric"=> "950"
  },
  {
    "priority"=> 100,
    "iso_code"=> "XCD",
    "name"=> "East Caribbean Dollar",
    "symbol"=> "$",
    "subunit"=> "Cent",
    "subunit_to_unit"=> 100,
    "symbol_first"=> true,
    "html_entity"=> "$",
    "decimal_mark"=> ".",
    "thousands_separator"=> ",",
    "iso_numeric"=> "951"
  },
  {
    "priority"=> 100,
    "iso_code"=> "XOF",
    "name"=> "West African Cfa Franc",
    "symbol"=> "Fr",
    "subunit"=> "Centime",
    "subunit_to_unit"=> 100,
    "symbol_first"=> false,
    "html_entity"=> "",
    "decimal_mark"=> ".",
    "thousands_separator"=> ",",
    "iso_numeric"=> "952"
  },
  {
    "priority"=> 100,
    "iso_code"=> "XPF",
    "name"=> "Cfp Franc",
    "symbol"=> "Fr",
    "subunit"=> "Centime",
    "subunit_to_unit"=> 100,
    "symbol_first"=> false,
    "html_entity"=> "",
    "decimal_mark"=> ".",
    "thousands_separator"=> ",",
    "iso_numeric"=> "953"
  },
  {
    "priority"=> 100,
    "iso_code"=> "YER",
    "name"=> "Yemeni Rial",
    "subunit"=> "Fils",
    "subunit_to_unit"=> 100,
    "symbol_first"=> false,
    "html_entity"=> "&#xFDFC;",
    "decimal_mark"=> ".",
    "thousands_separator"=> ",",
    "iso_numeric"=> "886"
  },
  {
    "iso_code"=> "ZAR",
    "name"=> "South African Rand",
    "symbol"=> "R",
    "html_entity"=> "&#x0052;"
  },
  {
    "iso_code"=> "ZMK",
    "name"=> "Zambian Kwacha",
    "symbol"=> "ZK",
    "html_entity"=> ""
  },
  {
    "iso_code"=> "ZWD",
    "name"=> "Zimbabwean Dollar",
    "symbol"=> "$",
    "html_entity"=> "$"
  }
]
CURRENCIES_MAP = []

CURRENCIES.each do |cur| 
  display = cur["html_entity"].blank? ? cur['iso_code'] : "#{cur['html_entity']} - #{cur['iso_code']}"
  # CURRENCIES_MAP << [display, cur["iso_code"]]
  CURRENCIES_MAP << cur["iso_code"]
end