source 'http://rubygems.org'

gem 'rails', '3.1.2'
gem 'json'
gem 'will_paginate', '3.0.pre2'
gem 'devise'
gem 'pg'

gem 'twilio-ruby'

gem "omniauth-facebook"
gem "omniauth-twitter"
gem 'omniauth-google-apps'
gem 'omniauth-linkedin'
gem "omniauth-salesforce"
gem 'databasedotcom'
gem 'databasedotcom-rails'
gem "highrise"

gem 'mysql2'
gem 'sqlite3'

group :assets do
  gem 'sass'
  gem 'coffee-script'
  gem 'uglifier'
  gem 'therubyracer'
end

gem 'jquery-rails'
gem 'jquery_datepicker'
gem 'thin', :group => [:production]

group :development do 
  gem 'debugger'
end

